<script type="text/template" id="coursepress-slugs-setting-tpl">
	<div class="cp-box-heading">
		<h2 class="box-heading-title"><?php _e( 'URL Slugs', 'cp' ); ?></h2>
        <p><?php _e( 'A slug is a few words that describe a post or a page. Slugs are usually a URL friendly version of the post title ( which has been automatically generated by WordPress ), but a slug can be anything you like. Slugs are meant to be used with permalinks as they help describe what the content at the URL is. Post slug substitutes the "<b>%posttitle%</b>" placeholder in a custom permalink structure.', 'CoursePress' ); ?></p>
        <p class="cp-info"><span class="dashicons dashicons-info"></span> <b>SITEROOT</b> = <?php echo home_url(); ?>/</p>
	</div>
<?php
$option_name = sprintf( 'coursepress_%s', basename( __FILE__, '.php' ) );
$GLOBALS['CoursePress_Admin_Configuration']->print_options( $option_name );
?>
</script>
