<?php $page = $_GET['page']; ?>

<div id="poststuff" class="metabox-holder m-settings">
    <form action='' method='post'>

        <input type='hidden' name='page' value='<?php echo $page; ?>' />
        <input type='hidden' name='action' value='updateoptions' />

        <?php
        wp_nonce_field('update-coursepress-options');
        ?>
        <div class="postbox">
            <h3 class="hndle" style='cursor:auto;'><span><?php _e('Slugs', 'cp'); ?></span></h3>
            <div class="inside">
                <p class='description'><?php _e('A slug is a few words that describe a post or a page. Slugs are usually a URL friendly version of the post title (which has been automatically generated by WordPress), but a slug can be anything you like. Slugs are meant to be used with <a href="options-permalink.php">permalinks</a> as they help describe what the content at the URL is. Post slug substitutes the <strong>"%posttitle%"</strong> placeholder in a custom permalink structure.', 'cp'); ?></p>
                <table class="form-table">
                    <tbody>
                        <tr valign="top">
                            <th scope="row"><?php _e('Course Slug', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url()));
                                ?>&nbsp;<input type='text' name='option_coursepress_course_slug' id='course_slug' value='<?php esc_attr_e($this->get_course_slug());
                                ?>' />&nbsp;/
                                
                                <p class='description'><?php _e('Your course URL will look like: ', 'cp'); ?><?php echo esc_html_e(trailingslashit(site_url()));?><?php echo esc_attr_e($this->get_course_slug());?><?php _e('/example-course-name/', 'cp');?></p>
                                
                            </td>
                        </tr>
                        
                        <tr valign="top">
                            <th scope="row"><?php _e('Units Slug', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url())).''._e('example-course-name/', 'cp');
                                ?>&nbsp;<input type='text' name='option_coursepress_units_slug' id='units_slug' value='<?php esc_attr_e($this->get_units_slug());
                                ?>' />&nbsp;/
                               
                            </td>
                        </tr>
                        
                        <tr valign="top">
                            <th scope="row"><?php _e('Course Notifications Slug', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url())).''._e('example-course-name/', 'cp');
                                ?>&nbsp;<input type='text' name='option_coursepress_notifications_slug' id='notifications_slug' value='<?php esc_attr_e($this->get_notifications_slug());
                                ?>' />&nbsp;/
                            </td>
                        </tr>
                        
                        <tr valign="top">
                            <th scope="row"><?php _e('Course Discussions Slug', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url())).''._e('example-course-name/', 'cp');
                                ?>&nbsp;<input type='text' name='option_coursepress_discussion_slug' id='discussion_slug' value='<?php esc_attr_e($this->get_discussion_slug());
                                ?>' />&nbsp;/
                            </td>
                        </tr>
                        
                        <tr valign="top">
                            <th scope="row"><?php _e('Course New Discussions Slug', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url())).''._e('example-course-name/', 'cp'); echo ''.$this->get_discussion_slug().'/';
                                ?>&nbsp;<input type='text' name='option_coursepress_discussion_slug_new' id='discussion_slug_new' value='<?php esc_attr_e($this->get_discussion_slug_new());
                                ?>' />&nbsp;/
                            </td>
                        </tr>
                        
                        <tr valign="top">
                            <th scope="row"><?php _e('Course Grades Slug', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url())).''._e('example-course-name/', 'cp');
                                ?>&nbsp;<input type='text' name='option_coursepress_grades_slug' id='discussion_slug' value='<?php esc_attr_e($this->get_grades_slug());
                                ?>' />&nbsp;/
                            </td>
                        </tr>
                        
                        <tr valign="top">
                            <th scope="row"><?php _e('Enrollment Process page', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url()));
                                ?>&nbsp;<input type='text' name='option_enrollment_process_slug' id='enrollment_process_slug' value='<?php esc_attr_e($this->get_enrollment_process_slug());
                                ?>' />&nbsp;/
                            </td>
                        </tr>
                        
                        <tr valign="top">
                            <th scope="row"><?php _e('Sign Up page', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url()));
                                ?>&nbsp;<input type='text' name='option_signup_slug' id='signup_slug' value='<?php esc_attr_e($this->get_signup_slug());
                                ?>' />&nbsp;/
                            </td>
                        </tr>
                        
                        <tr valign="top">
                            <th scope="row"><?php _e('Student Dashboard page', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url()));
                                ?>&nbsp;<input type='text' name='option_student_dashboard_slug' id='student_dashboard_slug' value='<?php esc_attr_e($this->get_student_dashboard_slug());
                                ?>' />&nbsp;/
                            </td>
                        </tr>
                        
                        <tr valign="top">
                            <th scope="row"><?php _e('Student Settings page', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url()));
                                ?>&nbsp;<input type='text' name='option_student_settings_slug' id='student_dashboard_slug' value='<?php esc_attr_e($this->get_student_settings_slug());
                                ?>' />&nbsp;/
                            </td>
                        </tr>
                        
                        <tr valign="top">
                            <th scope="row"><?php _e('Instructor profile slug', 'cp'); ?></th>
                            <td>
                                <?php
                                esc_html_e(trailingslashit(site_url()));
                                ?>&nbsp;<input type='text' name='option_instructor_profile_slug' id='instructor_profile_slug' value='<?php esc_attr_e($this->get_instructor_profile_slug());
                                ?>' />&nbsp;/
                            </td>
                        </tr>                        
                        
                    </tbody>
                </table>
            </div>
        </div>
        
         <div class="postbox">
            <h3 class="hndle" style='cursor:auto;'><span><?php _e('Theme Menu Items', 'cp'); ?></span></h3>
            <div class="inside">
                <p class='description'><?php _e('Whether to attach additional plugin menu items automatically (Courses, Student Dashboard, Log Out etc.) to the theme menu on front. Note: theme <strong>must have defined a Primary Menu</strong> <!--(with at least one item)--> in order to attach new menu items to it.', 'cp'); ?></p>
                <table class="form-table">
                    <tbody>
                        <tr valign="top">
                            <th scope="row"><?php _e('Display menu items', 'cp'); ?></th>
                            <td>
                                <input type='checkbox' name='display_menu_items' <?php echo ((get_option('display_menu_items', 1)) ? 'checked' : ''); ?> />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
         </div>

        <?php
        do_action('coursepress_general_options_page');
        ?>

        <p class="save-shanges">
            <?php submit_button(__('Save Changes', 'cp')); ?>
        </p>

    </form>
</div>