<?php
/**
 * Class CoursePress_Step_InputText
 */
class CoursePress_Step_InputText extends CoursePress_Step_Written {
	public function setUpStepMeta() {
		parent::setUpStepMeta(); // TODO: Change the autogenerated stub

		$question = $this->__get( 'post_content' );
		$questions = array(
			array(
				'type' => 'written',
				'title' => $this->__get( 'post_title' ),
				'question' => strip_tags( $question ),
				'placeholder_text' => $this->__get( 'placeholder_text' ),
				'word_limit' => 0,
			),
		);
		$this->__set( 'questions', $questions );
		$this->__set( 'module_type', 'input-written' );
	}
}
