<?php
/**
 * Class CoursePress_Step_Radio
 * Note*: Legacy class to handle module `input-radio`
 *
 * @since 3.0
 * @package CoursePress
 */
class CoursePress_Step_Radio extends CoursePress_Step_Quiz {
	public function setUpStepMeta() {
		parent::setUpStepMeta(); // TODO: Change the autogenerated stub

		$questions = $this->get_questions_data();
		$this->__set( 'questions', $questions );
		$this->__set( 'meta_questions', $questions );
		$this->__set( 'module_type', 'input-quiz' );
	}

	protected function get_questions_data() {
		$answers = $this->__get( 'answers' );
		$selected_answers = $this->__get( 'answers_selected' );
		$checked = array();

		foreach ( $answers as $pos => $answer ) {
			$checked[ $pos ] = (int) $pos === (int) $selected_answers;
		}

		return array(
			array(
				'type' => 'radio',
				'question' => '',
				'options' => array(
					'answers' => $answers,
					'checked' => $checked,
				),
			),
		);
	}
}
